USE PRACTICE;

SELECT * FROM policies;

SELECT * FROM brokers;

--changing Datatypees of the table(Policies Table)
ALTER TABLE policies ALTER COLUMN PolicyID INT NOT NULL;
ALTER TABLE policies ALTER COLUMN BrokerID INT NOT NULL;
ALTER TABLE policies ALTER COLUMN Premium INT;

--Assigning Primary Key 
ALTER TABLE policies ADD PRIMARY KEY(PolicyID);


--Changing Datatypes of the table(brokers Table)
ALTER TABLE brokers ALTER COLUMN BrokerID INT NOT NULL;
ALTER TABLE brokers ALTER COLUMN BrokerName nvarchar(30);
ALTER TABLE brokers ALTER COLUMN ReportsTo INT;

--Change Float values to Integers 
UPDATE brokers 
SET ReportsTo = CAST(CAST(ReportsTo AS FLOAT) AS INT)
WHERE ReportsTo IS NOT NULL;

--Investigate Column datatypes
EXEC sp_columns @table_name = 'brokers';
EXEC sp_columns @table_name = 'policies';



--Altering the broker table 
--2nd Row
UPDATE  brokers SET ReportsTo = 1
WHERE BrokerID = 2;
--3rd Row 
UPDATE brokers SET ReportsTo = 2
WHERE BrokerID = 3;
--4th Row 
UPDATE brokers SET ReportsTo = 3
WHERE BrokerID = 4;
--5th Row 
UPDATE brokers SET ReportsTo = 4
WHERE BrokerID = 5;

--Recursive CTE Question
--Question1: Given a broker, show all sub-brokers and agents under them—at all levels—and the total premiums generated under that hierarchy.
WITH BrokerHeirarchy AS (
SELECT BrokerID, BrokerName, ReportsTo,
  0 AS LevelDepth
  FROM brokers
  Where BrokerID = 1 
  
  UNION ALL 
  SELECT 
		b.BrokerID,
		b.Brokername,
		b.ReportsTo,
		bh.LevelDepth + 1
FROM Brokers b
INNER JOIN BrokerHeirarchy bh
		ON b.ReportsTo = bh.BrokerID
		)
SELECT * FROM BrokerHeirarchy
ORDER BY LevelDepth, BrokerID;


--Unique Broker
SELECT COUNT(DISTINCT(BrokerID)) FROM brokers;
SELECT COUNT(DISTINCT(BrokerName)) FROM brokers;

---Total Premium generated under RegionA
SELECT BrokerID FROM brokers
WHERE BrokerID = 2;

SELECT BrokerID FROM brokers
WHERE ReportsTo = 2;
--Total Premium generated by Brokers who report Directly to Region A
SELECT p.BrokerID, SUM(p.premium) AS TotalPremium FROM policies p
RIGHT JOIN brokers b ON p.BrokerID = b.BrokerID
WHERE  b.ReportsTo =2
GROUP BY p.BrokerID;

--Total Premium Genreated by Brokers Under Region A 
WITH BrokerHeirarchy AS (
	SELECT BrokerID
	FROM Brokers
	WHERE BrokerID = 2

	UNION ALL

	SELECT b.BrokerID
	FROM brokers b
	INNER JOIN BrokerHeirarchy bh
		ON b.ReportsTo = bh.BrokerID
)

SELECT SUM(p.premium) AS TotalPremium
FROM BrokerHeirarchy bh
LEFT JOIN Policies p ON p.BrokerID = bh.BrokerID;


--Total Premium Generated
SELECT SUM(Premium) As totalPremium FROM policies;


WITH broker_id_cte AS (
SELECT b.BrokerID, b.BrokerName, p.Premium, b.ReportsTo FROM brokers b
LEFT JOIN policies p
ON b.BrokerID = p.BrokerID
)
---SELECT * from broker_id_cte;
SELECT BrokerID, BrokerName, ReportsTo, SUM(Premium) AS Total_Premium,
DENSE_RANK()OVER(PARTITION  BY BrokerName ORDER BY SUM(Premium)  DESC) AS Ranked_brokers
FROM broker_id_cte
GROUP BY BrokerID, BrokerName;

SELECT  * FROM policies 
WHERE BrokerID = 46;

---Determine the Brokers who collect more money($) Per Month 
SELECT b.BrokerID, b.BrokerName, SUM(p.Premium) As Total_Premium , b.ReportsTo
--DENSE_RANK()OVER (PARTITION BY b.BrokerID ORDER BY SUM(p.Premium) DESC) AS ranked_broker
FROM brokers b 
LEFT JOIN policies p
ON b.BrokerID = p.BrokerID 
GROUP BY b.BrokerID, b.BrokerName, b.ReportsTo
ORDER BY Total_Premium DESC
;


--Any Duplicates in the PolicyID columns
SELECT PolicyID, COUNT(DISTINCT(PolicyID)) AS Total_apperances FROM policies
GROUP BY PolicyID;

---Method11(Robust)
SELECT
    PolicyID,
    COUNT(*) AS CountOfDuplicates
FROM
policies
GROUP BY
  PolicyID
HAVING
    COUNT(*) > 1;

--Premium Customers
SELECT PolicyID, Premium FROM policies
ORDER BY premium DESC;